# University of Liverpool 
# Maths and Statistics for AI and Data Science
## Practical Assessment – 1
## David Cushing
## MSc Data Science and AI

---

## Question 1:

a) Function $f(x)=2x+3,g(x)=x^3$. Find f∘g and inverse of f∘g.   (5 marks)  

b) Find the derivative of the functions $f(x)=sin⁡x ln cos⁡2x+6e^x$     (5 marks)  

c) Find the critical points for function $f(x)=-x^3+6x^2+15x+4, x∈R$, and state if the critical points are minima or maxima. (10 marks)  


#### a) The composite function $f∘g = f(g(x))$

$x \Rightarrow g(x) \Rightarrow f(g(x))$  Apply function g, then f, to x  
$x=x$   
$g(x)=x^3$  
$f(x^3)=2x^3+3$  


To find the inverse, apply the algebra in the reverse order...
  
$x \Rightarrow x^3 \Rightarrow x2 \Rightarrow +3$  
Inverse:    
$((x-3)/2)^{1/3} \Leftarrow x^{1/3} \Leftarrow /2 \Leftarrow -3$  


#### b) Derivative of $f(x)=sin⁡x ln cos⁡2x+6e^x$  

Use the product Rule: $(f.g)'=f'.g + f.g'$  

$f=sin(x)$                  
$f'(x)=cos(x)$  
$g=lncos2x+6e^x$            
$g'(x)= ????$  

To find $g'(x)$ we use the Chain Rule: 

$F'(x)= f'(g(x)).g'(x)$ 

Leibnitz notation, if y=f(u) and u=g(x), then: 
 
$\frac{dy}{dx} = \frac{dy}{du}.\frac{du}{dx}$  

Substitute into the Chain Rule to get:  

$ \frac{dy}{dx} = \frac{1}{cos2x+6x^x} .\frac{d}{dx}(cos2x+6e^x)$ 

$ \frac{dy}{dx} = \frac{1}{cos2x+6x^x} . -2sin(2x)+6e^x$   

$ g'(x)= \frac{dy}{dx} = \frac{-2sin(2x)+6e^x}{cos2x+6x^x}$ 

Substitute back into the original Product Rule:  

$f'(x) = cos(x)(lncos2x+6e^x) + sin(x)\frac{-2sin(2x)+6e^x}{cos2x+6x^x}$   








#### c) Find the critical points for function $f(x)=-x^3+6x^2+15x+4, x∈R$, and state if the critical points are minima or maxima.

Critical value is where $f'(x)=0$  

Using the power rule:   

$f'(x) = -3x^2 + 12x +15$   

Factorise the quadratic:

$(-3x+15)(x+1)$

The critical points of the quadratic are therefore $x=-1$ and $x=5$   

Calculate whether these are minima or maxima by calculating $f''(x)$ to see if they are positive or negative:

$f''(x) = -6x + 12$  

f''(-1) = 18

f''(5) = -24

---  


## Question 2:

Function $f(x,y)=x^2 y^3+y^2+2x(y+1)$. Suppose the initial values are given $x_0=1,y_0=0$ , and the learning rate is set to 0.01. 

a) Perform one iteration of the gradient descent algorithm.   (10 marks)   

b) Find the Hessian matrix of $f(x,y)$.     (10 marks)    



a) Gradient decent function is: $P_{n+1} = P_{n} - \eta \nabla f(P_{n})$   

Calculate  $\nabla f = (\frac{\partial f}{\partial x} , \frac{\partial f}{\partial y})$   

Partial differentials treat external variables as constants. 

$\frac{\partial }{\partial x} x^2y^3 + y^2 + 2xy + 2x$

$= 2xy^3 + 2y + 2$  

$= 2(xy^3 + y + 1)$  

$\frac{\partial }{\partial y} x^2y^3 + y^2 + 2xy + 2x$   

$ = 3x^2y^2 + 2y + 2x$   

$ = 2(\frac{3}{2}x^2y^2 + y + x)$    

At point $x_0=1,y_0=0$ :  

$\frac{df}{dx} = 2$    

$\frac{df}{dy} = 2$   

$\nabla f = (2,2)$    

Calculate first iteration of gradient decent at $x=1, y=0$ using $P_{n+1} = P_{n} - \eta \nabla f(P_{n})$, where $\eta = 0.01$    

$P_{n+1} = (1,0) - 0.01(2,2)$   

$P_{n+1} = (1,0) - (0.02,0.02)$ 

$P_{n+1} = (0.998, -0.02)$   






b) Find the Hessian matrix of $f(x,y)$.      

The Hassian is the square matrix of the second-order partial derivatives: 

First calculate the 2nd order partials using the power rule:

$\frac{\partial f}{\partial x} = 2xy^3 + 2y + 2$  

$\frac{\partial^{2} f}{\partial x^2} = 2y^3$

$\frac{\partial f}{\partial y} = 3x^2y^2 + 2y + 2x$  

$\frac{\partial^{2} f}{\partial y^2} = 6x^2y + 2$

$\frac{\partial^{2} f}{\partial x\partial y} = \frac{\partial^{2} f}{\partial y\partial x}= 6xy^2 + 2 \, \Rightarrow$  (Partially differeniate $\frac{\partial f}{\partial y}$ wrt to x, or visa versa)     

General 2x2 Hessian matrix:

$\begin{pmatrix}
\frac{\partial^{2} f}{\partial x^2} & \frac{\partial^{2} f}{\partial y\partial x} \\
\frac{\partial^{2} f}{\partial x\partial y} & \frac{\partial^{2} f}{\partial y^2}
\end{pmatrix}$   

Substitute in the partial differentials: 

$\begin{pmatrix}
2y^3 & 6xy^2 + 2 \\
6xy^2 + 2 & 6x^2y + 2 
\end{pmatrix}$   

---


## Question 3

Take this system of linear equations:

$\left\{ \begin{matrix}
x+y-z=-3 \\
2x+3y-8z=-18 \\
5x+6y-10z=-25 \\
\end{matrix} \right\}$   

a)  Write this system as a Matrix vector equation   (5 marks)

b)  Calculate the determinant and thereby determine if there is a unique solution to this system of equations   (5 marks)

c)  Write this as an augmented matrix and solve this system of equations. (10 marks)


#### a) Write this system as a Matrix vector equation

$\begin{vmatrix}
1 & 1 & -1\\
2 & 3 & -8\\
5 & 6 & -10
\end{vmatrix}
\begin{vmatrix}
x \\
y \\
z
\end{vmatrix} = 
\begin{vmatrix}
-3 \\
-18 \\
-25
\end{vmatrix}
$

#### b) Calculate the determinant and thereby determine if there is a unique solution to this system of equations

Determinant of a 3x3 matrix can be found using: 

$\begin{vmatrix}
A
\end{vmatrix} = a. 
\begin{vmatrix}
e & f\\
h & i
\end{vmatrix} - b.
\begin{vmatrix}
b & f\\
g & i
\end{vmatrix} + c. 
\begin{vmatrix}
d & e\\
g & h
\end{vmatrix}
$

Substituting values from the 3x3 matrix:

$\mid A\mid = 1 \mid -30+24 \mid -1 \mid -20+40 \mid -1 \mid 12-15 \mid  $   

$\mid A\mid = -6-20+3 = -23 $    

Determinatants of the coefficients $\neq 0, \Rightarrow$ it is a unique solution  

#### Write this as an augmented matrix and solve this system of equations.

Augmented matrix: 

$\begin{vmatrix}
1 & 1 & -1 & \mid -3\\
2 & 3 & -8 & \mid -18\\
5 & 6 & -10 & \mid -25
\end{vmatrix}$  

$R2 \Rightarrow R2 - 2R1$     
$\begin{vmatrix}
1 & 1 & -1 & \mid -3\\
0 & 1 & -6 & \mid -12\\
5 & 6 & -10 & \mid -25
\end{vmatrix}$   

$R3 \Rightarrow R3 - 5R1$     
$\begin{vmatrix}
1 & 1 & -1 & \mid -3\\
0 & 1 & -6 & \mid -12\\
0 & 1 & -5 & \mid -10
\end{vmatrix}$   

$R3 \Rightarrow R3 - R2$     
$\begin{vmatrix}
1 & 1 & -1 & \mid -3\\
0 & 1 & -6 & \mid -12\\
0 & 0 & 1 & \mid 2
\end{vmatrix}$   

$R2 \Rightarrow R2 + 6R3$     
$\begin{vmatrix}
1 & 1 & -1 & \mid -3\\
0 & 1 & 0 & \mid 0\\
0 & 0 & 1 & \mid 2
\end{vmatrix}$   

$R1 \Rightarrow R1 - R2$     
$\begin{vmatrix}
1 & 0 & -1 & \mid -3\\
0 & 1 & 0 & \mid 0\\
0 & 0 & 1 & \mid 2
\end{vmatrix}$   

$R1 \Rightarrow R1 - R2$     
$\begin{vmatrix}
1 & 0 & 0 & \mid -1\\
0 & 1 & 0 & \mid 0\\
0 & 0 & 1 & \mid 2
\end{vmatrix}$ 

$ x = -1, y = 0, z = 2 $

Substitute into original linear equations to verify:

$x + y - z = -3 \Rightarrow -1 + 0 -2 = -3 \\ 
2x + 3y - 8z = -18 \Rightarrow -2 + 0 -16 = -18 \\
5x + 6y - 10z = -25 \rightarrow -5 + 0 -20 = -25 \\$  

---

## Question 4
For a linear transformation $T: R^3  → R^4.$ $\begin{pmatrix}
2x_{1} + 3x_{2} + x_{3} \\
x_{1} - 3x_{2} \\
x_{1} + x_{2} + x_{3} \\
3x_{1} + 2x_{2} + x_{3}
\end{pmatrix}$

a) Determine the transformation matrix A.   (5 marks)

b) Determine rank(A).    (5 marks)

c) Find the kernel and image of transformation T, and their dimension.   (10 marks)

Provide appropriate justification and explanation to all your answers, detailing the methods used.


#### a)  Determine the transformation matrix A.

The transformation matrix can be found by applying the unit vector in each direction to the transformation: 

$ A = \begin{vmatrix}
T(\vec{e_{1}}), & T(\vec{e_{2}}), & T(\vec{e_{3}}) \\
\end{vmatrix}$   

Where: 

$\vec{e_{1}} = \begin{vmatrix}
1\\ 
0\\
0\\
0
\end{vmatrix}$  

$\vec{e_{2}} = \begin{vmatrix}
0\\ 
1\\
0\\
0
\end{vmatrix}$

$\vec{e_{3}} = \begin{vmatrix}
0\\ 
0\\
1\\
0
\end{vmatrix}$  

Apply the unit vectors to the transformation: 

$ T(\vec{e_{1}}) = T \begin{vmatrix} 1\\ 0\\ 0\\ 0 \end{vmatrix}  =  \begin{vmatrix} 2\\ 1\\ 1\\ 3 \end{vmatrix}$

$ T(\vec{e_{2}}) = T \begin{vmatrix} 0\\ 1\\ 0\\ 0 \end{vmatrix}  =  \begin{vmatrix} 3\\ -3\\ 1\\ 2 \end{vmatrix}$

$ T(\vec{e_{3}}) = T \begin{vmatrix} 0\\ 0\\ 1\\ 0 \end{vmatrix}  =  \begin{vmatrix} 1\\ 0\\ 1\\ 1 \end{vmatrix}$

Transformation matrix A:

$A = \begin{vmatrix}
2 & 3 & 1\\ 
1 & -3 & 0 \\
1 & 1 & 1\\
3 & 2 & 1
\end{vmatrix}$ 

#### b) Determine rank(A)

To determine the rank of a matrix, we reduce the matrix by row echelon method. The number of non-zero rows is the rank: 

$A = \begin{vmatrix}
2 & 3 & 1\\ 
1 & -3 & 0 \\
1 & 1 & 1\\
3 & 2 & 1
\end{vmatrix}$   

$ R_{1} \rightarrow R_{1} - R_{3} \\    
\begin{vmatrix}
1 & 2 & 0\\ 
1 & -3 & 0 \\
1 & 1 & 1\\
3 & 2 & 1
\end{vmatrix}$  

$ R_{2} \rightarrow R_{2} - R_{1} \\    
\begin{vmatrix}
1 & 2 & 0\\ 
0 & -5 & 0 \\
1 & 1 & 1\\
3 & 2 & 1
\end{vmatrix}$  

$ R_{4} \rightarrow R_{4} - 3R_{1} \\    
\begin{vmatrix}
1 & 2 & 0\\ 
0 & -5 & 0 \\
1 & 1 & 1\\
0 & -4 & 1
\end{vmatrix}$

$ R_{3} \rightarrow R_{3} - R_{1} \\    
\begin{vmatrix}
1 & 2 & 0\\ 
0 & -5 & 0 \\
0 & -1 & 1\\
0 & -4 & 1
\end{vmatrix}$

$ R_{2} \rightarrow R_{2} + 4R_{3} \\    
\begin{vmatrix}
1 & 2 & 0\\ 
0 & 1 & 4 \\
0 & -1 & 1\\
0 & -4 & 1
\end{vmatrix}$  

$ R_{3} \rightarrow R_{3} + R_{2} \\    
\begin{vmatrix}
1 & 2 & 0\\ 
0 & 1 & 4 \\
0 & 0 & 5\\
0 & -4 & 1
\end{vmatrix}$  

$ R_{4} \rightarrow R_{4} + 4R_{2} \\    
\begin{vmatrix}
1 & 2 & 0\\ 
0 & 1 & 4 \\
0 & 0 & 5\\
0 & 0 & 5
\end{vmatrix}$

$ R_{4} \rightarrow R_{4} - R_{3} \\    
\begin{vmatrix}
1 & 2 & 0\\ 
0 & 1 & 4 \\
0 & 0 & 5\\
0 & 0 & 0
\end{vmatrix}$  

$ R_{4} \rightarrow R_{4} / 5 \\    
\begin{vmatrix}
1 & 2 & 0\\ 
0 & 1 & 4 \\
0 & 0 & 1\\
0 & 0 & 0
\end{vmatrix}$  

$ R_{2} \rightarrow R_{2} - 4R_{3} \\    
\begin{vmatrix}
1 & 2 & 0\\ 
0 & 1 & 0 \\
0 & 0 & 1\\
0 & 0 & 0
\end{vmatrix}$  

$ R_{1} \rightarrow R_{2} - 2R_{2} \\    
\begin{vmatrix}
1 & 0 & 0\\ 
0 & 1 & 0 \\
0 & 0 & 1\\
0 & 0 & 0
\end{vmatrix}$

The matrix has been manipulated into reduced row echelon form. The number of non-zero rows is the rank. 
Therefore the rank of A is 3.  

#### c) Find the kernel and image of transformation T, and their dimension.

Our transformation is :

$\begin{pmatrix}
2 & 3 & 1\\ 
1 & -3 & 0 \\
1 & 1 & 1\\
3 & 2 & 1
\end{pmatrix}
\begin{pmatrix}
x_{1} \\
x_{2} \\
x_{3}
\end{pmatrix} =
\begin{pmatrix}
2x_{1} + 3x_{2} + x_{3} \\
x_{1} - 3x_{2} \\
x_{1} + x_{2} + x_{3} \\
3x_{1} + 2x_{2} + x_{3}
\end{pmatrix}$
 
A Kernal, the subspace of the vector of the linear transformation which is mapped to the zero vector,  is a set of solutions to the homogenous linear equation $Ax = 0$ 

In part (b) A was reduced to give a solution for this equation: 

$\begin{vmatrix}
1 & 0 & 0\\ 
0 & 1 & 0 \\
0 & 0 & 1\\
0 & 0 & 0
\end{vmatrix}
\begin{vmatrix}
x_{1} \\
x_{2} \\
x_{3}
\end{vmatrix} =
\begin{vmatrix} 0 \\ 0 \\ 0 \\ 0\end{vmatrix}
$

As the reduced row echelon form is fully reduced, then the solution of $Ax = 0$ is unique, and the nullspace only contains the zero vector, and therefore this is the kernal. 

$dim(Ker(T))=0$

The image is the range of vectors in a vector space -  the span of the vectors. This is the vectors you calculate when you apply the linear transform.
In reduced row echelon form, the image basis of the matrix comprises of the columns that contain a leading 1.  

Note: 
If S is a subset of a vector space V.
(i) Then span(S) is a subspace of V that contains S.
(ii) If W is a subspace of V containing S, then $span(S) \subseteq W$.

$ Im(T) = span(A) = span \begin{pmatrix}
\begin{vmatrix} 1 \\ 0 \\ 0\\ 0 \end{vmatrix} , \begin{vmatrix} 0 \\ 1 \\ 0\\ 0 \end{vmatrix} , \begin{vmatrix} 0 \\ 0 \\ 1\\ 0 \end{vmatrix}
\end{pmatrix} $

The Dimension is defined as: 

$  dim(Im(T)) = rank(A) = 3$ 


---



## Question 5

Matrix $A=\begin{vmatrix}
2 & -3 \\ 
1 & 6  
\end{vmatrix}$ 

a) Determine the inverse of matrix A.    (5 marks)

b) Find the singular value decomposition (SVD) of matrix A.    (10 marks)

c) Given the SVD of matrix, find the SVD of $A^T$.   (5 marks)

Provide appropriate justification and explanation to all your answers, detailing the methods used.


#### a) Determine the inverse of matrix A

The inverse of a 2x2 matrix can be found using the equation: 

$A^{-1} = \frac{1}{(ad - bc)}  \begin{vmatrix} d & -b \\ -c & a \end{vmatrix}$   

$A^{-1} = \frac{1}{(12 + 3)}  \begin{vmatrix} 6 & 3 \\ -1 & 2 \end{vmatrix}$

$A^{-1} = \begin{vmatrix} \frac{6}{15} & \frac{3}{15} \\ \\ \frac{-1}{15} & \frac{2}{15} \end{vmatrix}$





#### b) Find the singular value decomposition (SVD) of matrix A.

For a matrix $A \in \mathbb{R}^{mxm}$ of rank $r \in [0, min(m,n)]$. The SVD of A is a decomposition of the form:

$$ A= U \Sigma V^T $$ 

* Where $U \in \mathbb{R}^{mxm}$ is an orthogonal matrix with column vector $u_{i} (i = 1, ... , m)$.

    * Matrix U diagonalizes $AA^T$

    * $u_{i}'$ s are called left-singular vectors and are eigenvectors of $AA^T$.

* $V \in \mathbb{R}^{nxn}$ is an orthogonal matrix with column vector $v_i (i = 1, ... , n)$.

    * Matrix V diagonalizes $A^TA$.

    * $v_{i}'$ s are called left-singular vectors and are eigenvectors of $A^TA$.

* $\Sigma \in \mathbb{R}^{mxn}$ is a diagonal matrix with $\Sigma_{ii} = \sigma_i \geq 0$ and  $\Sigma_{ij} = 0. $
$\sigma_i$ is called the singular values of A. 

    * $\sigma_i$ is the square roots of the eigenvalues of $A^TA$.

Calculating $AA^T$ :

$\begin{vmatrix} 2 & -3 \\ 1 & 6 \end{vmatrix} \cdot \begin{vmatrix} 2 & 1 \\ -3 & 6 \end{vmatrix}$   

$AA^T$ = $\begin{vmatrix} 13 & -16 \\ -16 & 37 \end{vmatrix}$

Eigenvalues are the roots of the characteristic equation $(A - \lambda I) = 0 $

Calculate the Eigenvalues from the characteristic polynomial: 

If A = $\begin{vmatrix} a & b \\ c & d \end{vmatrix}$

$\Delta t = t^2 - (a + d)t + det(A)$   

   $= t^2 - (13 + 37)t + (481-256)$

   $= t^2 - 50t + 225$

Factorise:  $(t-5)(t-45)$ , which give roots at 5 and 45, and singular values at $\sqrt{5}$ and $\sqrt{45}$

Using $(A - \lambda I)$ = $\begin{vmatrix} 13-\lambda & -16 \\ -16 & 37-\lambda \end{vmatrix}$

Substitute in $\lambda = 45$ 

$\begin{vmatrix} -32 & -16 \\ -16 & -8 \end{vmatrix}$

Row reduce to find the eigenvector: 

$ R_{2} \rightarrow R_{2} - 0.5R_{1} \\    
\begin{vmatrix}
-32 & -16 \\ 
0 & 0 \\
\end{vmatrix}$

$ R_{1} \rightarrow R_{1} / -32\\    
\begin{vmatrix}
1 & 0.5 \\ 
0 & 0 \\
\end{vmatrix}$

Therefore the eigenvector for $\lambda =45$ is $\begin{vmatrix} -0.5 \\ 1 \end{vmatrix}$

The magnitude of this eigenvector is $\sqrt(0.5^2 + 1^2) = 1.118033989$ 

And it's unit vector is $\begin{vmatrix} -0.5 \\ 1 \end{vmatrix} /1.118033989 = \begin{vmatrix} −0.447213595 \\ 0.894427191 \end{vmatrix} $

Repeat for  $\lambda = 5$

$\begin{vmatrix} 8 & -16 \\ -16 & 32 \end{vmatrix}$

Row reduce to find eigenvector:

$ R_{2} \rightarrow R_{2} + 2R_{1} \\    
\begin{vmatrix}
8 & -16 \\ 
0 & 0 \\
\end{vmatrix}$

$ R_{1} \rightarrow R_{1} / 8 \\    
\begin{vmatrix}
1 & -2 \\ 
0 & 0 \\
\end{vmatrix}$

Therefore the eigenvector for for $\lambda =5$ is $\begin{vmatrix} 2 \\ 1 \end{vmatrix}$

The magnitude of this eigenvector is $\sqrt(2^2 + 1^2) = 2.236067977$ 

And it's unit vector is $\begin{vmatrix} 2 \\ 1 \end{vmatrix} /2.236067977 = \begin{vmatrix} 0.894427191 \\ 0.447213596 \end{vmatrix} $   

Therefore U is the matrix of the unit vectors: 

$U =  \begin{vmatrix}
−0.447213595 & 0.894427191 \\ 
0.894427191 & 0.447213596 \\
\end{vmatrix}$

And $\Sigma$ is the diagonal of the sigma values:

$\begin{vmatrix}
\sqrt{45} & 0 \\ 
0 &  \sqrt{5} \\
\end{vmatrix}$

Calculating V: 

Left-singular vectors are the image of the right-sided singular vectors under A. We normalise them by dividingby their corresponding singular value: 

Each vector is = $\frac{1}{\sigma_i} \cdot A^T \cdot u_i$

first vector $ = \frac{1}{\sqrt45} \cdot \begin{vmatrix} 2 & 1 \\ -3 & 6 \end{vmatrix} \cdot \begin{vmatrix} −0.447213595 \\ 0.894427191 \end{vmatrix} $

$ = \begin{vmatrix} 0 \\ 1 \end{vmatrix}$

second vector $ = \frac{1}{\sqrt5} \cdot \begin{vmatrix} 2 & 1 \\ -3 & 6 \end{vmatrix} \cdot \begin{vmatrix} 0.894427191 \\ 0.447213596 \end{vmatrix} $

$ = \begin{vmatrix} 1 \\ 0 \end{vmatrix}$

Therefore the Matrix V is: $ = \begin{vmatrix} 1 & 0\\ 0 & 1 \end{vmatrix}$

$SVD = U \Sigma V^T$

$SVD = \begin{vmatrix} −0.447213595 & 0.894427191 \\ 0.894427191 & 0.447213596 \end{vmatrix} \cdot \begin{vmatrix}\sqrt{45} & 0 \\0 &  \sqrt{5} \end{vmatrix} \cdot \begin{vmatrix} 1 & 0\\ 0 & 1 \end{vmatrix}$


         

In [7]:
#### Checking SVD using the code given in Week 4 :

# This task is to practice singular value decomposition (SVD)

import numpy as np
from scipy import linalg

print('Checking SVD using the code given in Week 4 :')

# 2 x 3 matrix
A = np.array([[2, -3],
               [1, 6]])

U, Sigma, V_T = np.linalg.svd(A)

print(f'Left orthogonal matrix for A:\n{np.round(U, 2)}\n')

# Display singular values along the diagonal of sigma matrix.
print(f'Singular values diagonal matrix for A:\n{np.round(Sigma, 2)}\n')

print(f'Right orthogonal matrix for A:\n{np.round(V_T, 2)}') 


Checking SVD using the code given in Week 4 :
Left orthogonal matrix for A:
[[-0.45 -0.89]
 [ 0.89 -0.45]]

Singular values diagonal matrix for A:
[6.71 2.24]

Right orthogonal matrix for A:
[[ 0.  1.]
 [-1. -0.]]


#### c) Given the SVD of matrix, find the SVD of $A^T$.

$A^T=\begin{vmatrix}
2 & 1 \\ 
-3 & 6  
\end{vmatrix}$ 

For transposed matrix $U = V_{original}$ and $V = U_{original}$

Therefore the SVD of $A^T$ is 

$SVD = U \Sigma V^T$

$SVD = \begin{vmatrix} 1 & 0\\ 0 & 1 \end{vmatrix} \cdot \begin{vmatrix}\sqrt{45} & 0 \\0 &  \sqrt{5} \end{vmatrix} \cdot \begin{vmatrix} −0.447213595 & 0.894427191 \\ 0.894427191 & 0.447213596 \end{vmatrix} $


In [8]:
#### Checking SVD using the code given in Week 4 :

# This task is to practice singular value decomposition (SVD)

import numpy as np
from scipy import linalg

print('Checking SVD using the code given in Week 4 :')

# 2 x 3 matrix
A = np.array([[2, 1],
               [-3, 6]])

U, Sigma, V_T = np.linalg.svd(A)

print(f'Left orthogonal matrix for A:\n{np.round(U, 2)}\n')

# Display singular values along the diagonal of sigma matrix.
print(f'Singular values diagonal matrix for A:\n{np.round(Sigma, 2)}\n')

print(f'Right orthogonal matrix for A:\n{np.round(V_T, 2)}') 


Checking SVD using the code given in Week 4 :
Left orthogonal matrix for A:
[[0. 1.]
 [1. 0.]]

Singular values diagonal matrix for A:
[6.71 2.24]

Right orthogonal matrix for A:
[[-0.45  0.89]
 [ 0.89  0.45]]


---

### Bibliography:

Lipschutz, S. & Lipson, M. (2008), 'Schaum's Outline of Linear Algebra', 4th Edition, McGraw-Hill Professional Publishing.

Penney, R. C., (2015), 'Linear Algebra: Ideas and Applications', 4th edition, John Wiley & Sons, Inc.

Stewart, J. (2008), - ‘Calculus: Metric International Version’, Cengage Learning

Stroud, K.A, and  Booth, D. J. (2008), ‘Engineering Mathematics’, Palgrave Macmillan

Aziz, K. A. (2020), 'Learn How to Write Markdown & LaTeX in The Jupyter Notebook', blog available at https://towardsdatascience.com/write-markdown-latex-in-the-jupyter-notebook-10985edb91fd  




##### Written using Markdown and Latex on Visual Studio Code

End
